"""Add causelist parsing fields

Revision ID: 05ad37e58a90
Revises: 0003_add_user_profile_fields
Create Date: 2026-05-13 08:14:11.063717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '05ad37e58a90'
down_revision: Union[str, Sequence[str], None] = '0003_add_user_profile_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('causelist_bench', sa.Column('jurisdiction_groups_json', sa.Text(), nullable=True))
    op.add_column('causelist_bench', sa.Column('scheduling_notes_json', sa.Text(), nullable=True))
    op.add_column('causelist_bench', sa.Column('hearing_start_time', sa.String(), nullable=True))
    op.add_column('causelist_bench', sa.Column('mentioning_allowed', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('causelist_case', sa.Column('case_time_annotation', sa.String(), nullable=True))
    op.add_column('causelist_case', sa.Column('is_part_heard', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('causelist_case', sa.Column('next_date_annotation', sa.String(), nullable=True))
    op.add_column('causelist_case', sa.Column('is_with_case', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('causelist_case', sa.Column('parent_serial_no', sa.Integer(), nullable=True))
    op.add_column('causelist_case', sa.Column('linked_case_ref', sa.Text(), nullable=True))
    op.add_column('causelist_case', sa.Column('bench_id_footer', sa.String(), nullable=True))
    op.add_column('causelist_case', sa.Column('group_no', sa.String(), nullable=True))
    op.add_column('causelist_case', sa.Column('canonical_section', sa.String(), nullable=True))
    op.drop_index(op.f('idx_cc_advocate_trgm'), table_name='causelist_case', postgresql_ops={'advocate': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_cc_petitioner_trgm'), table_name='causelist_case', postgresql_ops={'petitioner': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_cc_respondent_trgm'), table_name='causelist_case', postgresql_ops={'respondent': 'gin_trgm_ops'}, postgresql_using='gin')
    op.alter_column('email_otps', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('email_otps', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('email_otps', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('email_otps', 'otp_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('email_otps', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('email_otps', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_email_otps_email'), table_name='email_otps')
    op.drop_index(op.f('idx_email_otps_user'), table_name='email_otps')
    op.drop_index(op.f('idx_phone_otps_phone'), table_name='phone_otps')
    op.create_foreign_key(None, 'tracked_cases', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('idx_users_phone'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_users_phone'), 'users', ['phone'], unique=False)
    op.drop_constraint(None, 'tracked_cases', type_='foreignkey')
    op.create_index(op.f('idx_phone_otps_phone'), 'phone_otps', ['phone'], unique=False)
    op.create_index(op.f('idx_email_otps_user'), 'email_otps', ['user_id'], unique=False)
    op.create_index(op.f('idx_email_otps_email'), 'email_otps', ['email'], unique=False)
    op.alter_column('email_otps', 'created_at',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('email_otps', 'expires_at',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('email_otps', 'otp_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('email_otps', 'user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('email_otps', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('email_otps', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('idx_cc_respondent_trgm'), 'causelist_case', ['respondent'], unique=False, postgresql_ops={'respondent': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_cc_petitioner_trgm'), 'causelist_case', ['petitioner'], unique=False, postgresql_ops={'petitioner': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_cc_advocate_trgm'), 'causelist_case', ['advocate'], unique=False, postgresql_ops={'advocate': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_column('causelist_case', 'canonical_section')
    op.drop_column('causelist_case', 'group_no')
    op.drop_column('causelist_case', 'bench_id_footer')
    op.drop_column('causelist_case', 'linked_case_ref')
    op.drop_column('causelist_case', 'parent_serial_no')
    op.drop_column('causelist_case', 'is_with_case')
    op.drop_column('causelist_case', 'next_date_annotation')
    op.drop_column('causelist_case', 'is_part_heard')
    op.drop_column('causelist_case', 'case_time_annotation')
    op.drop_column('causelist_bench', 'mentioning_allowed')
    op.drop_column('causelist_bench', 'hearing_start_time')
    op.drop_column('causelist_bench', 'scheduling_notes_json')
    op.drop_column('causelist_bench', 'jurisdiction_groups_json')
    # ### end Alembic commands ###
