"""sync_schema_fix

Revision ID: 4558de5b9871
Revises: 05ad37e58a90
Create Date: 2026-05-14 14:42:21.352307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4558de5b9871'
down_revision: Union[str, Sequence[str], None] = '05ad37e58a90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_case_history_cache_fetched'), table_name='case_history_cache')
    op.drop_table('case_history_cache')
    op.drop_index(op.f('idx_cc_advocate_trgm'), table_name='causelist_case', postgresql_ops={'advocate': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_cc_petitioner_trgm'), table_name='causelist_case', postgresql_ops={'petitioner': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_cc_respondent_trgm'), table_name='causelist_case', postgresql_ops={'respondent': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_email_otps_email'), table_name='email_otps')
    op.drop_index(op.f('idx_email_otps_user'), table_name='email_otps')
    op.drop_index(op.f('idx_phone_otps_phone'), table_name='phone_otps')
    op.drop_index(op.f('idx_tracked_cases_cino'), table_name='tracked_cases')
    op.drop_index(op.f('idx_tracked_cases_refresh'), table_name='tracked_cases')
    op.create_index('idx_tracked_cases_refresh', 'tracked_cases', ['court_no', 'list_date'], unique=False)
    op.create_foreign_key(None, 'tracked_cases', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('idx_users_phone'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_users_phone'), 'users', ['phone'], unique=False)
    op.drop_constraint(None, 'tracked_cases', type_='foreignkey')
    op.drop_index('idx_tracked_cases_refresh', table_name='tracked_cases')
    op.create_index(op.f('idx_tracked_cases_refresh'), 'tracked_cases', ['state_cd', 'court_code', 'case_type_id'], unique=False)
    op.create_index(op.f('idx_tracked_cases_cino'), 'tracked_cases', ['cino'], unique=False)
    op.create_index(op.f('idx_phone_otps_phone'), 'phone_otps', ['phone'], unique=False)
    op.create_index(op.f('idx_email_otps_user'), 'email_otps', ['user_id'], unique=False)
    op.create_index(op.f('idx_email_otps_email'), 'email_otps', ['email'], unique=False)
    op.create_index(op.f('idx_cc_respondent_trgm'), 'causelist_case', ['respondent'], unique=False, postgresql_ops={'respondent': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_cc_petitioner_trgm'), 'causelist_case', ['petitioner'], unique=False, postgresql_ops={'petitioner': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_cc_advocate_trgm'), 'causelist_case', ['advocate'], unique=False, postgresql_ops={'advocate': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_table('case_history_cache',
    sa.Column('cino', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('state_cd', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('court_code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('case_type_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('case_no', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('case_year', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('data_json', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('fetched_at', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('cino', 'state_cd', 'court_code', name=op.f('case_history_cache_pkey'))
    )
    op.create_index(op.f('idx_case_history_cache_fetched'), 'case_history_cache', [sa.literal_column('fetched_at DESC')], unique=False)
    # ### end Alembic commands ###
